### ISSUE TITLE
Not a lot of Japanese characters

### ISSUE THREAD

**Issue by GamerIsNotEg** [cooolgamer/3DS-custom-keyboard#3]
So in some games I want exactly the Japanese name that I want but I cannot do that because the keyboard doesn’t come with Hiragana characters so could you please add them because I would really appreciate it

**Comment by CZ2746isback** [comment]
> So in some games I want exactly the Japanese name that I want but I cannot do that because the keyboard doesn’t come with Hiragana characters so could you please add them because I would really appreciate it

The hiragana/katakana can be swapped by changing the shift. You can cycle through the characters by repeatedly tapping on the character.

**Comment by dunk61** [comment]
btw, isn't it missing the ぱぴぷぺぽ sounds?

**Comment by cooolgamer** [comment]
sorry for late response, here's an image with the phone japanese keyboard strings:
![image](https://user-images.githubusercontent.com/64099608/205346564-1fa84664-895a-417f-8c6f-1dc29630219a.png)
for me they're all there

**Comment by dunk61** [comment]
oh, they're in the m-row? i probably just didn't notice it then, my bad.

**Comment by cooolgamer** [comment]
yeah, could've moved them here but it would be too long

**Comment by cooolgamer** [comment]
they got moved btw, in case you're wondering
