### ISSUE TITLE
DS Software doesn't know what an "A" Button is

### ISSUE THREAD

**Issue by PigletTubeYT** [cooolgamer/3DS-custom-keyboard#5]
![CCDF8D8D-00DA-4CDA-A9B2-EC657A7C9FD4](https://user-images.githubusercontent.com/106480112/221381629-2a50c765-ed29-4d4b-a200-53b4a5fa7d45.jpeg)

**Comment by cooolgamer** [comment]
this isn't related to the keyboard, it's just the DS font not having it
