### ISSUE TITLE
More characters

### ISSUE THREAD

**Issue by ghost** [cooolgamer/3DS-custom-keyboard#6]
Some secret characters are missing, like the home icons, little wii text icon, playcoin icon, there is more in the DS files as well, can you please include them.

**Comment by cooolgamer** [comment]
Those are only for games that uses this font, I think you talk about mario kart 7, if you pick some custom symbols, they get replaced with others such as wii, home icon, friend icon etc. it's due to the game's font, the keyboard have nothing to do with that

**Comment by ghost** [comment]
![IMG_20240328_040516_808](https://github.com/cooolgamer/3DS-custom-keyboard/assets/120220827/786029c0-acd8-46d9-b6ab-cea1ee890b5b)
![IMG_20240328_040456_106](https://github.com/cooolgamer/3DS-custom-keyboard/assets/120220827/3ece0849-fe98-4d07-8145-5ed58dc14fb2)
![IMG_20240328_040532_881](https://github.com/cooolgamer/3DS-custom-keyboard/assets/120220827/6fa9e69c-19f3-4e6f-9d5b-032b3193bae2)
![Uploading IMG_20240328_040547_640.jpg…]()

**Comment by ghost** [comment]
They are not just fonts, they all exist in the files and can be entered using hacked keyboards or save editors, again, please add them to the keyboard.

**Comment by ghost** [comment]
![IMG_20240328_040547_640](https://github.com/cooolgamer/3DS-custom-keyboard/assets/120220827/7ab42e4f-6eb5-419c-879d-28b90cecb00e)

**Comment by ghost** [comment]
![Screenshot_20240328-104641_1](https://github.com/cooolgamer/3DS-custom-keyboard/assets/120220827/2cd0d3f2-78a7-463d-abf6-94d9537fd281)
I wonder how many hidden characters exist

**Comment by cooolgamer** [comment]
Yeah that's what I thought, they're on the custom keyboard already, just press the shift (a<=>A) button to show the "missing" ones
