### ISSUE TITLE
Add Nintendo Switch/Wii U Symbols on the keyboard

### ISSUE THREAD

**Issue by BurstClouds23** [cooolgamer/3DS-custom-keyboard#7]
Hi, I some other custom keyboard that includes special symbols for Switch, it would be good to be added too

![image](https://github.com/cooolgamer/3DS-custom-keyboard/assets/131524279/96873362-d9e5-4c4e-9c3e-a854809d1d71)
![image](https://github.com/cooolgamer/3DS-custom-keyboard/assets/131524279/390d3827-4601-4150-b474-3eef7a25260b)

**Comment by Official3Gamer** [comment]
![loading](https://github.com/cooolgamer/3DS-custom-keyboard/assets/140297634/93cbca35-f7d3-42fe-8852-58e93df90ab7)
Intresting

**Comment by cooolgamer** [comment]
I don't see the point of doing this as it shows as [?] On 3ds, yes you can transfer miis to show them but the keyboard run out of space for new characters so this won't be implemented.
